plugins { id 'com.android.application' }

android {
    namespace 'kz.medetakbolat.twin'
    compileSdk 35

    defaultConfig {
        applicationId 'kz.medetakbolat.twin'
        minSdk 23
        targetSdk 30
        versionCode 3
        versionName '1.2.0'
    }

    signingConfigs {
        debug {
            enableV1Signing = true
            enableV2Signing = true
            enableV3Signing = true
            enableV4Signing = false
        }
    }

    buildTypes {
        debug { signingConfig signingConfigs.debug }
        release {
            signingConfig signingConfigs.debug
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint { checkReleaseBuilds false; abortOnError false }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.core:core:1.13.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.media3:media3-exoplayer:1.4.1'
    implementation 'androidx.media3:media3-ui:1.4.1'
    implementation 'androidx.media3:media3-session:1.4.1'
}
