plugins { id 'com.android.application' }

android {
    namespace 'com.onebell.app'
    compileSdk 35

    defaultConfig {
        applicationId 'kz.medetakbolat.onebell'
        minSdk 21
        targetSdk 30
        versionCode 5
        versionName '1.0.4'
    }

    signingConfigs {
        debug {
            enableV1Signing = true
            enableV2Signing = true
            enableV3Signing = true
            enableV4Signing = false
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.debug
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
